all done
maksym-slinchenko/goit-node-hw-01 pull request #1
Opened 2021-04-15 21:57 UTC by maksym-slinchenko

2021-04-19 16:49 UTC, SergeiKBB requested changes

2021-04-19 16:49 UTC, SergeiKBB commented on contacts.js
> +    let maxId = ids[0];
Если ты уже решил сам создавать айди, почему ты не заюзал готовый метод з `Math` для получения максимального значения з массива? Я б все равно рекомендовал бы использовать какуюту либку для генерации айдишников

2021-04-19 16:49 UTC, SergeiKBB commented on contacts.js
> +  fs.readFile(contactsPath, "utf-8", (err, data) => {
Почему бы не сделать ретерн контактов с этой функции и ты смог бы использовать её дальше в коде для получения списка контактов? А выводил бы в таблицу непосредствено в файле index.js

2021-04-19 16:49 UTC, SergeiKBB commented on contacts.js
> +function getContactById(id) {
Перепиши пожалуйста все функции на async await

2021-04-20 06:49 UTC, maksym-slinchenko commented on contacts.js
> +    let maxId = ids[0];
Не сразу разобрался как применить Math.max для массива. Уже погуглил и разобрался, но в итоге как ты и рекомендуешь заюзал библиотеку для коротких id. Почему сразу не использовал библиотеку, потому что в базовом json-файле id были представленны в виде набора простых чисел. Думал по аналогии и продолжать...

2021-04-20 06:50 UTC, maksym-slinchenko commented on contacts.js
> +  fs.readFile(contactsPath, "utf-8", (err, data) => {
Изначально так и хотел сделать, но не могу разобраться почему эта функция у меня возвращает undefined. Уже крутил ее по всякому, но безрезультатно. Можешь помочь разобраться?

// ?????????????????????
async function getContacts() {
  fs.readFile(contactsPath, "utf-8", (err, data) => {
    if (err) {
      console.log(err.message);
      return;
    }
    const contacts = JSON.parse(data);
    return contacts;
  });
}

console.log(getContacts()); // Promise { undefined }
// ??????????????????????

2021-04-20 06:50 UTC, maksym-slinchenko commented on contacts.js
> +function getContactById(id) {
Переписал. Еще не привык)

2021-04-20 08:11 UTC, SergeiKBB commented on contacts.js
> +  fs.readFile(contactsPath, "utf-8", (err, data) => {
Потому что тебе нужно асинхроно использовать fs.readFile а не колбеком

2021-04-20 22:52 UTC, maksym-slinchenko commented on contacts.js
> +  fs.readFile(contactsPath, "utf-8", (err, data) => {
Я застрял с этим fs.readFile. Поможешь разобраться? Спасибо! 

async function get() {
  await fs.readFile(contactsPath, "utf-8", (err, data) => {
    if (err) {
      console.log(err.message);
      return;
    }
    const contacts = JSON.parse(data);
    return contacts;
  });
}
console.log(get()); //  Promise { <pending> }

2021-04-21 18:54 UTC, SergeiKBB commented on contacts.js
> +  fs.readFile(contactsPath, "utf-8", (err, data) => {
async function listContacts() {
    try {
      const data = await fs.readFile(contactsPath), "utf-8");
      return JSON.parse(data)
    } catch (e) {
      console.error(e)
    }
}

2021-04-21 21:23 UTC, maksym-slinchenko commented on contacts.js
> +  fs.readFile(contactsPath, "utf-8", (err, data) => {
Этот способ тоже не помог. Получилось только с использованием fs.readFileSync. Не знаю на сколько это законно)

2021-04-23 08:42 UTC, merged